#!/bin/bash

git add -A
git commit -m "Abort test"
git checkout -b workshop-step4 step4
git merge step4-test1 > /dev/null
git checkout --ours .
git add .
git commit -m "Merge with test branch"

echo ""
echo ""

printf '\033[0;32m'
cat stepsDoc/step4.txt
printf '\033[0m'

echo ""
echo ""
